AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create Security Groups for Public and Private EC2 Instances.

Resources:

  # Tạo VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  # Public Security Group (cho phép SSH từ một IP cụ thể)
  PublicEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow SSH from specific IP
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 192.168.1.29/32  # Thay thế x.x.x.x bằng địa chỉ IP của bạn
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0  # Cho phép tất cả outbound traffic
      Tags:
        - Key: Name
          Value: PublicEC2SecurityGroup

  # Private Security Group (cho phép SSH từ Public EC2 instance)
  PrivateEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow SSH from public EC2 instance
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicEC2SecurityGroup  # Chỉ cho phép từ Public SG
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0  # Cho phép tất cả outbound traffic
      Tags:
        - Key: Name
          Value: PrivateEC2SecurityGroup

Outputs:
  PublicEC2SecurityGroupID:
    Description: The ID of the Public EC2 Security Group
    Value: !Ref PublicEC2SecurityGroup

  PrivateEC2SecurityGroupID:
    Description: The ID of the Private EC2 Security Group
    Value: !Ref PrivateEC2SecurityGroup
